CREATE TABLE student (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college VARCHAR(255),
    course VARCHAR(255),
    email VARCHAR(255),
    graduation_year INTEGER,
    name VARCHAR(255)
);

CREATE TABLE project (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     description VARCHAR(255),
     title VARCHAR(255),
     student_id INTEGER,
     CONSTRAINT fk_project_student
        FOREIGN KEY (student_id)
        REFERENCES student(id)
);
