CREATE TABLE company(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    description VARCHAR(255),
    website VARCHAR(255),
    location VARCHAR(255)
);