CREATE TABLE job(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    location VARCHAR(255),
    employment_type VARCHAR(255),
    salary NUMERIC(12, 2),
    company_id INTEGER,

    CONSTRAINT fk_job_company
        FOREIGN KEY (company_id)
        REFERENCES company(id)
);